# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Specify a common set of lints using rustflags for all targets.
[target.'cfg(all())']
rustflags = [
  # Disable FPO to get full call stack as the '--call-graph=dwarf' option
  # is not working well.
  "-Cforce-frame-pointers=yes",

  # Enable v0 symbols to get better output from `perf` and related tools.
  "-Csymbol-mangling-version=v0",

### ENABLE_IN_CI "-Dwarnings",

]