[package]
name = "elfcore"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(unix)'.dependencies]
libc.workspace = true
nix.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
zerocopy.workspace = true
